### ISSUE TITLE
ImportError: cannot import name Entity

### ISSUE THREAD

**Issue by vineetabajaj** [MAECProject/pefile-to-maec#9]
im getting this import error. Can anyone help in resolving this issue.

![snapshot](https://cloud.githubusercontent.com/assets/26162225/23558574/2895a4b4-005a-11e7-95bb-e4e329efd9dd.png)

**Comment by gtback** [comment]
Hi @vineetabajaj: as with #8, it looks like you have incompatible versions of python-maec, python-cybox, and mixbox. Can you run "pip list" and include the versions of all three of those libraries (they will show up as `maec`, `cybox`, and `mixbox`)?

We've made some fairly significant changes to all of those libraries since we've updated pefile-to-maec. Our intent was that the changes would be transparent to pefile-to-maec, but it's possible some incompatibility snuck in. If you're sure you have the latest versions of all 3, let us know and we'll fix it.

**Comment by vineetabajaj** [comment]
sir,
I have tried with different versions and still im unable to run
pefile_to_maec.
can you help me with specific version on which i can work.

i have pip list attached , please find in attachments.

**Comment by vineetabajaj** [comment]
![snapshot123](https://cloud.githubusercontent.com/assets/26162225/23603706/3732db94-027c-11e7-88d0-a28a350253e2.png)

**Comment by gtback** [comment]
Thanks for the information, @vineetabajaj. I was able to confirm that the current version of `pefile-to-maec` doesn't work with the latest python-cybox and latest python-maec.

I've updated the README to reflect the versions you should use. You should be able to run `pip install cybox==2.1.0.12 maec==4.1.0.12`, and pefile-to-maec should work then.

**Comment by vineetabajaj** [comment]
Thanks for help. Error resolved

**Comment by gtback** [comment]
Glad that helped!
